config/routes.rb
Rails.application.routes.draw do
  root 'words#index'

  resources :words do
    resources :definitions
  end

  get 'contributors', to: 'static_pages#contributors'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/definition.rb
class Definition < ApplicationRecord
  belongs_to :word

  validates :word, presence: true
  validates :definition, presence: true
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :definitions

  validates :word, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :find_word

  def create
    @definition = @word.definitions.build(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @word, notice: 'Definition added.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render @word }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def find_word
    @word = Word.find(params[:word_id])
  end

  def find_definition
    @word = Word.find(params[:word_id])
  end

  def definition_params
    params.require(:definition).permit(:definition)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contributors
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/definitions/_form.html.erb
<%= form_for [word, definition] do |f| %>
  <%= f.text_area :definition %>
  <br />
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LwdDict</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="nav">
      <%= link_to 'Home', root_path %>
      | <%= link_to 'Contributors', contributors_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contributors.html.erb
<h1>Contributors</h1>
Here is a list of people that have contributed:
<ul>
    <li>Eric McKay</li>
    <li>John Laine</li>
</ul>

app/views/words/_form.html.erb
<%= form_for(word) do |f| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
  <% if @word.definitions %>
    <ul>
      <% @word.definitions.each do |d| %>
        <li><%= d.definition %></li>
      <% end %>
  <% end %>
</p>

<div>
  Add a definition.
  <%= render partial: 'definitions/form', locals: {
    word: @word,
    definition: Definition.new,
    word_id: @word.id
  } %>
</div>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>